### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [ArturoMoLo90/Proyecto_Final_Bioinf2017-II#2]
Ok, esperemos que lleguen los datos a principios de mes, pero si no ¿cuál sería tu plan b?

Veo que no has instalado Stacks y BWA. Para el segundo hay un biocontainers, por lo que no será un problema, pero Stacks URGE que lo instales lo más pronto posible y que pruebes que funcione con los datos de prueba que vienen en el tutorial.

**Comment by ArturoMoLo90** [comment]
Me acaban de matar las esperanzas, ya me dijo la encargada de la segunda parte del trabajo de laboratorio de mi proyecto que mis resultados no estaran si no hasta Agosto/Septiembre. Si esta bien, he optado por hacer lo siguiente: **procesar datos ddRAD crudos de _Berberis alpina_ y analizarlos de novo con una versión de Stacks distinta de la utilizada en el artículo o con otro programa.** ya que en definitiva con mis muestras no podre trabajar. ¿Como debo proceder con respecto a los avances que he subido? ¿Creo nuevos?

**Comment by AliciaMstt** [comment]
Qué lástima.

Crea un nuevo avance 2 que detalle esto y avísanos (por aquí) cuando esté para que le demos un ojo.

**Comment by ArturoMoLo90** [comment]
Hola Alicia, una disculpa pero estoy teniendo dificultades con el proyecto. Estuve intentando instalar stacks en mi computadora, lo cual ha sido un fracaso total, ya me intentaron ayudar pero, no he podido. Por lo cual ya opte por hacer el trabajo mejor en la computadora que esta en mi laboratorio. Ya tiene stacks instalado y funcionando. Por otra parte, quiero ver si me puedes orientar un poco con respecto a si ¿es necesario bajar las secuencias raw de B. alpina directamente de SRA, o de donde debo bajarlo? ya estuve revisando los datos que estan en el repositorio y no he encontrado dichas secuencias, igual tuve problemas con el archivo de la sección de "1.Running Stacks", no lograba descargarlo y descomprimirlo, tuve que utilizar una computadora diferente. En cuanto a las secuencias, ingrese al SRP035472 que marca en el articulo para bajar las secuencias y estoy tratando de instalar SRAtoolkit para poder bajar dichas secuencias, pero parece que no dara como tal las secuencias crudas, si no una tabla CSV para excel con la información de los "runs".

 En enserio una disculpa si voy atrasado con los tiempos de entrega del proyecto pero recientemente me han cargado de trabajo en el laboratorio (por ser el ultimo envío del año) y ando con varios pendientes por causa de un envío que tenemos que hacer en 15 días aproximadamente, lo cual me ha quitado demasiado tiempo.

**Comment by ArturoMoLo90** [comment]
Ya instale el SRAtoolkit y probe el siguiente comando: ./fastq-dump.2 (que en teoría deberia bajar todas las secuencias, pero al ingresarlo arroja lo siguiente:

 la-iMac-de-Laboratorio:bin laboratoriogenetica$ ./fastq-dump.2 SRP035472
2017-05-19T20:34:58 fastq-dump.2.8.2 err: item not found while constructing within virtual database module - the path 'SRP035472' cannot be opened as database or table

saludos

**Comment by AliciaMstt** [comment]
Hola Arturo, justamente por eso es que bajar las secuencias e instalar los programas deben ser el paso uno a hacer nada más decidir cuál sería el trabajo final.
Las secuencias las puedes bajar de SRA. Prueba https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=search_seq_name si el SRAtoolkit no te funciona y no logras solucionarlo.
